let arr = Array();
document.writeln(arr);
document.writeln("<br/>");
let arr2 = Array();
arr2[0] = "Ramesh";
arr2[1] = "Rajesh";
arr2[2] = "Sandeep";
arr2[3] = "Manish";
document.writeln(arr2);
document.writeln("<br/>");

let arr3 = Array();
arr3.push(100);
document.writeln(arr3);
document.writeln("<br/>");
arr3.push(200);
document.writeln(arr3);
document.writeln("<br/>");
arr3.push(300);
document.writeln(arr3);
document.writeln("<br/>");
arr3.pop();
document.writeln(arr3);
document.writeln("<br/>");
arr3.pop();
document.writeln(arr3);
document.writeln("<br/>");
arr3.pop();
document.writeln(arr3);
document.writeln("<br/>");
document.writeln(arr3);
document.writeln("<br/>");
arr3.pop();
document.writeln(arr3);
document.writeln("<br/>");